# Generated by Django 2.1.5 on 2019-01-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Author', max_length=25),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=models.TextField(default='Body'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(default='Subtitle', max_length=400),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Published '),
        ),
    ]
