# Generated by Django 2.1.5 on 2019-01-15 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0003_blogpost_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_author',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
