# Generated by Django 2.1.5 on 2019-02-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0007_blogpost_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
